// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { config as loadEnv } from "dotenv";
import path from "node:path";
import { defineConfig } from "prisma/config";

// Default `dotenv/config` only loads `.env`. Overlay `.env.local` so `npx prisma migrate` matches Next.js.
loadEnv({ path: path.join(process.cwd(), ".env.local"), override: true });

/** Prisma CLI (migrate, introspect) uses a direct connection; prefer DIRECT_URL over a pooler URL. */
function prismaDatasourceUrl(): string {
  return (
    process.env["DIRECT_URL"] ??
    process.env["DATABASE_URL"] ??
    ""
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: prismaDatasourceUrl(),
  },
});
